---
# name: .travis.yml
# description: This file tells travis, what needs to be done.
# author: style-cheat.io
# contact: hello@style-cheat.io
# license: BSD-3-Clause
# reference: https://docs.travis-ci.com/user/customizing-the-build

language: node_js
node_js:
  - "10"

install:
  # Install test dependencies.
  - npm install -g sass
  - npm install -g sass-lint

script:
  # Do the tests.
  sass-lint src/

notifications:
  email:
    recipients:
      - devel@style-cheat.io
    on_success: change
    on_failure: always

  irc:
    channels:
      - "chat.freenode.net#while-true-do"
    on_success: change
    on_failure: always
